### ISSUE TITLE
Improvement: Set quote item attribute no_discount to 1

### ISSUE THREAD

**Issue by sbothnermzentrale** [Smile-SA/magento2-module-gift-sales-rule#19]
Hello,

want to discuss an option where no_discount attribute for quote item is set to 1 to avoid processing of sales rules on free givaways. Would make it more strict and core based.

KR

**Comment by PierreLeMaguer** [comment]
Hello,

Sorry for the delay.
Can you detail your idea ?

Thanks,
Pierre
