### ISSUE TITLE
Gift product is not removed if condition changes

### ISSUE THREAD

**Issue by kolaente** [Smile-SA/magento2-module-gift-sales-rule#27]
We have the following rule set up: If the quantity of certain products in cart is either 1,3,5,7, etc., one gift product is added to the cart. When I put 1 of these products in cart, I get one gift product.
However, when I put 2 products in cart, the first gift product is not removed, it is still in cart. Since the rule evaluates to false for 2 products, I would expect it to remove already added products.

It is also possible to remove the product from cart while keeping the gifted product.

**Comment by amenk** [comment]
related to #4

**Comment by amenk** [comment]
is this related? https://github.com/Smile-SA/magento2-module-gift-sales-rule/blob/master/Observer/UpdateGiftRuleActions.php#L74

**Comment by amenk** [comment]
The module is doing really scary things. It relabels the actions and uses it for the free product selection. This does not work well. We resorted now to use https://github.com/code4business/freeproduct2 which is simpler and works :-)

**Comment by PierreLeMaguer** [comment]
Hello @kolaente ,

is the issue still present with the last version of the module ?

Thanks,
Pierre

**Comment by amenk** [comment]
Hi @PierreLeMaguer,
Thank you for checking back.
I am a colleague of @kolaente and we are no longer using this module.

**Comment by PierreLeMaguer** [comment]
Thanks for your answer and sorry for the delay.
I'm closing the issue.
