### ISSUE TITLE
Unclear "limit of gift products" on frontend.

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-gift-sales-rule#3]
I create a rule with "Maximum number product offered" (missing translation here :) ) = 2.

On the cart page, I choose one gift, then another. They appear in my cart as attended.

If I select another gift, I got the message "You added gift product to your shopping cart." but the product is not added.

Maybe in this case we should have a message indicating clearly that maximum number of gifted products has been reached on the current cart.

**Comment by maximequeneau** [comment]
Fix by frontend developpement. Now, it's not possible to add more product than defined in the rule.

**Comment by romainruaud** [comment]
Closed by associated PR.
