### ISSUE TITLE
Place order issue

### ISSUE THREAD

**Issue by jigsawyer** [Smile-SA/magento2-module-gift-sales-rule#30]
Hello. 
We faced loop issue, during place order , for which cart rule is applied. 
During payment method save
**vendor/magento/module-quote/Model/PaymentMethodManagement.php:52** is triggered CollectTotals process. And during this process triggered Observer **vendor/smile/module-gift-sales-rule/Observer/SetNumberOfferedProduct.php** ,in which quote is retrieved from session, and as it has TotalsCollected = false - process begin from scratch.
On the older version 1.1.0 - everything is OK.

**Module version 1.1.1**
**Magento version Cloud 2.3.5 -p2**

Best regards

**Comment by jigsawyer** [comment]
More information:
- error message on front https://prnt.sc/ura0nw
- error report  https://i.imgur.com/rWp05c3.png
- cart rule https://i.imgur.com/JtAcYy5.png

**Comment by PierreLeMaguer** [comment]
Hi,

I see, we will try to fix that as soon as possible.
We need to avoid to use the session quote here vendor/smile/module-gift-sales-rule/Observer/SetNumberOfferedProduct.php .
Thanks for the report of the issue !

**Comment by maximequeneau** [comment]
Fix by Pierre Le Maguer
