### ISSUE TITLE
Conditions of the rule not taken into account

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-gift-sales-rule#4]
I create a rule with following conditions : 

![image](https://user-images.githubusercontent.com/15340849/55000358-a0bd5580-4fd2-11e9-854c-18941bbb1ddc.png)

I add to my cart a product which is NOT the "24-WG02".

The rule is displayed in my cart and I can choose gifts, but it should no be the case.

![image](https://user-images.githubusercontent.com/15340849/55000459-d82c0200-4fd2-11e9-95ea-61e855f67aa0.png)

**Comment by romainruaud** [comment]
It looks like whatever the rule conditions, it's automatically applied (show in quote.applied_rule_ids) when I put a product into my cart.

**Comment by maximequeneau** [comment]
It's native Magento anomaly. I try with action "to offer product" and "Fixed amount discount for whole cart". When you clean cache and click on "Update Shopping Cart", the good conditions are used.

**Comment by amenk** [comment]
Is this still an issue? We couldn't solve it with clearing the caches.

**Comment by girishanand** [comment]
Hello @maximequeneau ,

Is there a possibility to add the conditions check for applying the rules in the current extension? The module works perfectly but does not take account of the conditions used.

Thankyou in advance for your reply.

**Comment by PierreLeMaguer** [comment]
Hello @girishanand ,

can you tell us if the issue is still here with the last version of the module ? In my side, I don't reproduce any more.

Thanks,
Pierre

**Comment by PierreLeMaguer** [comment]
issue closed because of inactivity, considered as resolved with the last version of the module
