### ISSUE TITLE
Apply only with reloading page

### ISSUE THREAD

**Issue by iloa08** [Smile-SA/magento2-module-gift-sales-rule#44]
Thanks for this module.
However I have a problem : the gift proposal appears only after reloading the page.
Am I the only one with this feat ?

**Comment by PierreLeMaguer** [comment]
Hello,

a similar issue was identified here https://github.com/Smile-SA/magento2-module-gift-sales-rule/issues/43 . We are working on it.
Can you tell us the magento version and the module version you are using ?
And if the configuraiton sales/msrp/enabled is enabled ?

Thanks,
Pierre

**Comment by iloa08** [comment]
Magento 2.3.3
magento2-module-gift-sales-rule-1.1.4
no MAP - no MSRP
Thanks

**Comment by iloa08** [comment]
Problem is always present on my test after updating.

**Comment by PierreLeMaguer** [comment]
Hello,

can you describe with more details how do you reproduce the issue ?
Magento Version ?
Gift Sales Rule Module Version ?
The configuration of your salesrule ?
The different steps to reproduce ?
Third module ?

Thanks,
Pierre

**Comment by iloa08** [comment]
Magento 2.3.3
your last version on github
no MAP - no MSRP

test with simple rule :
If ALL  of these conditions are TRUE 
    Subtotal  equals or greater than  200 
      
No Third module on checkout page
I can give you the url for test

Thanks

**Comment by PierreLeMaguer** [comment]
@iloa08 , Ok, thanks for your submission. We close this issue.
