### ISSUE TITLE
Conflict with claue theme

### ISSUE THREAD

**Issue by lucasfpiovesan12** [Smile-SA/magento2-module-gift-sales-rule#55]
I'm using the Claue theme, and give me this error in the shopping cart:

configurable.js:49 Uncaught TypeError: Cannot read property 'bind' of undefined

This error means that configurable product options do not appear.

What can it be?

![Seleção_107](https://user-images.githubusercontent.com/44383986/100934347-64433c00-34cd-11eb-8491-01906d2efd7f.png)
![Seleção_108](https://user-images.githubusercontent.com/44383986/100934351-64dbd280-34cd-11eb-8a62-a155c4f1bf43.png)
![Seleção_109](https://user-images.githubusercontent.com/44383986/100934353-65746900-34cd-11eb-885c-da2b9bed7954.png)

**Comment by PierreLeMaguer** [comment]
Hello,

Thanks for using this module ans submitting this issue.
Can you tell us the Magento version used ?
If it's > 2.4, maybe this PR https://github.com/Smile-SA/magento2-module-gift-sales-rule/pull/50 could resolve it.
If not, I suggest you to check in your theme (or globally in your code) if you make some customization on the file configurable.js ?

Thanks,
Pierre

**Comment by lucasfpiovesan12** [comment]
Magento 2.3.5

I updated the module and unfortunately it didn't work...

I don't know where to look now... 
Would you help me?

**Comment by PierreLeMaguer** [comment]
Hello,

I would advice to check every customization on the files Magento_ConfigurableProduct/js/configurable or Magento_Swatches/js/swatch-renderer or vendor/magento/module-swatches/view/frontend/templates/product/view/renderer.phtml or vendor/magento/module-configurable-product/view/frontend/templates/product/view/type/options/configurable.phtml which could affect gallery.

**Comment by PierreLeMaguer** [comment]
Hello @lucasfpiovesan12 ,

did you succeed to find and solve the issue ?

Thanks

**Comment by PierreLeMaguer** [comment]
Closed because of issue inactivity
