### ISSUE TITLE
Can't select gift product in cart rule creation

### ISSUE THREAD

**Issue by brigandi** [Smile-SA/magento2-module-gift-sales-rule#66]
Hi, Magento 2.4.
When I create the rule to add product for free I can't choose products. Under select gift product there is no option.

![screencapture-weed-love-it-admin-wdl-sales-rule-promo-quote-new-key-b047dbb869769c801ce88f12e9d548170eb4eb39cfd69321f77e6b7c72ddf420-2021-02-11-09_33_09](https://user-images.githubusercontent.com/78901320/107615327-3ce6b900-6c4c-11eb-9ac5-8a969e1cfeea.png)

**Comment by PierreLeMaguer** [comment]
Hello,

thanks for using this module.
Can you detail the exact Magento version and is it the commerce or opensource one ? Also, can you give the Gift sales rule module version used ?
I tested in Magento CE 2.4.1 and I succeed to select conditions under 'select gift product'.
![screenshot-magento-ce-2-4 lxc-2021 02 12-08_13_36](https://user-images.githubusercontent.com/19976778/107740552-b5607f00-6d0b-11eb-8581-13711719b2c1.png)
![screenshot-magento-ce-2-4 lxc-2021 02 12-08_14_28](https://user-images.githubusercontent.com/19976778/107740556-b72a4280-6d0b-11eb-91a9-1bbf81106633.png)
After save, the rule is well created.

Thanks,

**Comment by brigandi** [comment]
Hi, 
It is a 2.4 CE, I think it has been installed by composer so I suppose is the last one. It is under vendor/smile folder
Thanks

Amministratore VALKIRIA D.O.O.

Roberto Brigandì

Address: VERDIJEVA ULICA 001
KOPER - CAPODISTRIA
Registrazione: 89114370
Matična številka: 6894143000
Mobile: +393387819740

www.valkiriaeliquids.com <https://www.valkiriaeliquids.com/>

**Comment by PrigentMatthieu** [comment]
Pierre couldn't reproduce in 2021. Install the new version of the module on a up to date Magento. And if you still have an issue, please open a new issue. Thank you.
