### ISSUE TITLE
Free product based on product attribute condition not working

### ISSUE THREAD

**Issue by ronakchauhan** [Smile-SA/magento2-module-gift-sales-rule#67]
**Precondition:**
- Magneto  2.3.4
- PHP 7.3
- Nginx 1.16
- Smile Gift Sales Rule module version: 1.0.1

Step to Reproduce:

- Create new rule to add free gift product without coupon code
- Add condition like "SKU is xxxxxxx"
- Action like "SKU is xxxxxxx"
- Frontend -  Add to cart same product as applied condition and rule applied successfully
- Frontend - Add different product than mentioned in condition and still free product displayed in cart
- Issue is with all product attributes like "SKU, category, Size, Special price"etc.

Expected Result:

-  Free gift product should be in cart only for product applied in condition

Actual Result:

-  Free gift product in cart even if wrong product add in cart

<img width="1673" alt="Screen Shot 2021-05-26 at 16 24 47" src="https://user-images.githubusercontent.com/8565366/119678177-9d86b400-be3f-11eb-9d24-f153d7d01032.png">

**Comment by PierreLeMaguer** [comment]
Hello

Thanks for using this module.
You are using an old version of the module. I advise you to install the last version 1.1.8 which includes an important fix about rule conditions.

Regards,
