### ISSUE TITLE
Foreign key constraint fails when trying to save the new Cart Price Rule

### ISSUE THREAD

**Issue by artttj** [Smile-SA/magento2-module-gift-sales-rule#70]
**Precondition:**

- Magento Commerce 2.4.2-p1 in Magento Cloud.
- smile/module-gift-sales-rule, v1.1.8

**Steps to reproduce:**

Create a new Cart Price Rule.

**Expected result:**

The rule is successfully created.

**Actual result:**

Integrity constraint violation:
![image](https://user-images.githubusercontent.com/13865085/129184435-a06a2b34-4f19-4227-b944-95dcc549484a.png)

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dbname`.`smile_gift_salesrule`, CONSTRAINT `SMILE_GIFT_SALESRULE_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `smile_gift_salesrule` (`rule_id`, `maximum_number_product`, `price_range`) VALUES (?, ?, ?)
```

**Comment by artttj** [comment]
Seems like changing [this line](https://github.com/Smile-SA/magento2-module-gift-sales-rule/blob/master/Model/SalesRule/SaveHandler.php#L78) of code from:
`$ruleId = $entity->getData($metadata->getLinkField());`

to:
`$ruleId = $entity->getData($metadata->getIdentifierField());`

fixes the problem.

**Comment by artttj** [comment]
This happens when there are records in `salesrule` where `rule_id` and `row_id` are different.

**Comment by artttj** [comment]
Hi @PierreLeMaguer 

It looks like the foreign key in Magento Commerce should be the row_id? 

Based on this comment:
https://github.com/Smile-SA/magento2-module-gift-sales-rule/issues/60#issue-781910464

\<constraint xsi:type="foreign" referenceId="FL_ALLOWED_RULE_ID" table="smile_gift_salesrule"
            column="rule_id" referenceTable="salesrule" referenceColumn="~~rule_id~~**row_id**"
            onDelete="CASCADE"/\>

**Comment by PierreLeMaguer** [comment]
Hello @artttj ,

sorry for the delay.
Did you try to install this module https://github.com/Smile-SA/magento2-module-gift-sales-rule-staging ?

Thanks

**Comment by PierreLeMaguer** [comment]
The module https://github.com/Smile-SA/magento2-module-gift-sales-rule-staging should solve the issue. I close the issue because of the inactivity.
