### ISSUE TITLE
 Plugin class Magento\Multishipping\Plugin\DisableMultishippingMode doesn't exist

### ISSUE THREAD

**Issue by josneyr** [Smile-SA/magento2-module-gift-sales-rule#71]
Hello, I'm having this problem:

php -d memory_limit=8000M bin/magento setup:di:compile;
Compilation was started.
Interceptors generation... 4/7 [================>-----------]  57% 14 secs 241.0 MiB
In PluginList.php line 182:

  Plugin class Magento\Multishipping\Plugin\DisableMultishippingMode doesn't exist
  
------

  Magento version 2.3.2
  
  Do you know how to solve this?
  
  Thanks

**Comment by PierreLeMaguer** [comment]
Hello,

it looks like the last version of this module is not compatible with magento 2.3.2.
I would advice either to update Magento, or install the gift sales rule module version 1.1.6 (last version before the creation of the plugin on Magento\Multishipping\Plugin\DisableMultishippingMode)

**Comment by PierreLeMaguer** [comment]
Need to update the Readme to inform people about the version to install for Magento < 2.3.3
