### ISSUE TITLE
Theme conflict

### ISSUE THREAD

**Issue by khk-kit** [Smile-SA/magento2-module-gift-sales-rule#72]
Not working in magento 2 gemany theme. 
https://www.templatemonster.com/magento-themes/gemany-jewel-store-template-magento-theme-96048.html
Magento Luma theme it is working.

How to fix?

**Comment by PierreLeMaguer** [comment]
Hello,

I'm sorry, it's difficult to say something on how to fix without the source code of the germany theme.
If you find the bug and that there is something to change on the gift sales rule module, don't hesitate to say it.

Thanks

**Comment by PierreLeMaguer** [comment]
I close the issue because of the inactivity.
