### ISSUE TITLE
Backend orders not working

### ISSUE THREAD

**Issue by Mo3ta9em93** [Smile-SA/magento2-module-gift-sales-rule#73]
Hello,
I can't make an order from Magento 2 backend when a free gift rule applies.
an error shows "requested qty is not available" although qty is available for all products including gift products.

Thank you

**Comment by PierreLeMaguer** [comment]
Hello,

Can you show some screenshots and the detail of the sales rule applied ?
Can you detail the magento version and the gift sales rule module version ?
Moreover, unfortunately, we do not test a lot the create order from admin.
I will try to check this, but feel free to purpose a PR if you have time

Thanks
