### ISSUE TITLE
Button "Validate my gift(s)" should be always visible

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-gift-sales-rule#8]
Actually if there is a lot of potential gifts, I have to scroll to the bottom of the popin to see the button, which is a bit confusing.

The button should be outside of the "overflow:scroll" part (it's probably a bit complicated to do).

![image](https://user-images.githubusercontent.com/15340849/58032593-384aaa80-7b23-11e9-83d3-3b9ee3764562.png)

**Comment by PierreLeMaguer** [comment]
Is it what you thought about ?
![screenshot-magento-ce-2-3 lxc-2019 05 20-18-18-39](https://user-images.githubusercontent.com/19976778/58036695-0558e480-7b2c-11e9-8587-ba5e8e8a6822.png)

**Comment by romainruaud** [comment]
yep something like this would be fine !

**Comment by romainruaud** [comment]
Closed by associated PR.
